version: '3'

services:
   webserver:
      container_name: webserver_nginx
      image: nginx:latest 
      ports:
         - 9090:80
         - "8443:443"
 
   database:
      image: redis:latest
      ports:
         - 8080:81

